add vehicle on parking detection models
openvinotoolkit/training_extensions pull request #333
Opened 2020-08-13 09:25 UTC by ygnn123

2020-08-14 15:07 UTC, AlexanderDokuchaev commented on pytorch_toolkit/object_detection/vehicle-detection/readme.md
> +| vehicle-detection-0001 | 212.22 | 36.56 | 32.4 | [snapshot](https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-detection-0203.pth), [configuration file](
Names of models should be 0203,  0204, 0205

2020-08-14 15:09 UTC, AlexanderDokuchaev commented on pytorch_toolkit/object_detection/vehicle-detection/readme.md
> +For SSD networks (0200,0201,0201) an alternative OpenVINO™ representation is possible.
Missed 0202

2020-09-08 12:29 UTC, AlexanderDokuchaev commented
run tests

2020-09-10 07:59 UTC, Ilya-Krylov commented
run tests

2020-09-16 07:25 UTC, Ilya-Krylov commented
@ygnn123 There were some difficulties with export. Have you resolve them? We need to have tests on export and testing

2020-09-16 08:22 UTC, ygnn123 commented
There are not problems now.

2020-09-30 09:56 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/vehicle-detection/readme.md
> +| vehicle-detection-0003 | 212.22 | 36.56 | 32.4 | [snapshot](https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-detection-0203.pth), [configuration file](
@ygnn123 Will you fix these numbers?

2020-10-08 08:15 UTC, Ilya-Krylov commented
@ygnn123 please resolve conflicts and prepare template.yaml files

2020-10-13 13:37 UTC, Ilya-Krylov commented
@ygnn123 could you please bring approved test data (5-10 pictures) and expected quality metric value on it? Corresponding test is also needed (train, eval, export). Please have a look at `pytorch_toolkit/object_detection/tests/` folder.

2020-10-23 07:20 UTC, ygnn123 commented
> @ygnn123 could you please bring approved test data (5-10 pictures) and expected quality metric value on it? Corresponding test is also needed (train, eval, export). Please have a look at `pytorch_toolkit/object_detection/tests/` folder.

@Ilya-Krylov , good day!

CI fails during export step with error:
  File "../../../tools/export.py", line 42, in <module>
      if Config.fromfile(yaml.load(read_file, yaml.SafeLoader)['config']).model.bbox_head.type == 'SSDHead'
because CascadeRCNN config does not have bbox_head under model. It is under roi_head. Look here:
https://github.com/ygnn123/openvino_training_extensions/blob/yg/add_veh_park_det/pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0203/config.py

2020-11-10 11:43 UTC, Ilya-Krylov commented on .gitmodules
> +	url = https://github.com/openvinotoolkit/mmdetection.git
why? please use ../mmdetection

2020-11-12 10:30 UTC, Ilya-Krylov commented
@ygnn123 You also have some problems with documentation http://134.191.240.124/job/ote/job/precommit/job/documentation/725/console

2020-11-12 13:38 UTC, Ilya-Krylov commented
Please revert 'Submodule deep-object-reid deleted from ddde34'

2020-11-12 13:44 UTC, Ilya-Krylov requested changes

2020-11-12 13:44 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/model_templates/vehicle-detection/readme.md
> +| vehicle-detection-0004 | 190.32 | 34.15 | 47.3 | [snapshot](https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-detection-0204.pth), [model template](./ve
add empty line after the table, otherwise it is shown wrong

2020-11-12 13:44 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/tests/export_tests_vehicle_detection.py
> +    """ Test case for vehicle-detection-0230 model export. """
203

2020-11-12 13:44 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/model_templates/vehicle-detection/readme.md
> +| vehicle-detection-0003 | 112.34 | 24.11 | 43.8 | [snapshot](https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-detection-0203.pth), [model template](./ve
203

2020-11-12 13:44 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/model_templates/vehicle-detection/readme.md
> +| vehicle-detection-0004 | 190.32 | 34.15 | 47.3 | [snapshot](https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-detection-0204.pth), [model template](./ve
204

2020-11-12 18:19 UTC, Ilya-Krylov commented on .gitmodules
> +	url = https://github.com/openvinotoolkit/deep-object-reid.git
Relative paths!

2020-11-14 04:12 UTC, Ilya-Krylov commented
merdged https://github.com/openvinotoolkit/training_extensions/pull/370

2020-11-14 04:12 UTC, closed without merging