Add person-detection-0203 model
openvinotoolkit/training_extensions pull request #381
Opened 2020-12-02 17:34 UTC by GalyaZalesskaya

2020-12-10 11:30 UTC, GalyaZalesskaya commented
run tests

2020-12-11 10:43 UTC, GalyaZalesskaya commented
run tests

2020-12-15 07:02 UTC, Ilya-Krylov commented
run tests

2020-12-15 07:12 UTC, Ilya-Krylov approved these changes

2020-12-15 07:18 UTC, Ilya-Krylov commented
run tests

2020-12-15 07:20 UTC, Ilya-Krylov commented
run tests

2020-12-15 13:28 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/tests/export_tests_person_detection.py
> +            os.path.dirname(__file__) + '/../../../data/airport/annotation_example_train.json',
try to use proper annotation here and above 'annotation_person_train.json', I am fixing it in my PR. Looks like CI job is hanging on loading http://213.221.44.203/job/ote/job/precommit/job/pt_object_detection/505/consoleFull. I kill it.

2020-12-17 07:31 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/tests/expected_outputs/person-detection/person-detection-0203.json
> +{"map": 0.704}
for now, metric is measure in percent, 70.4 should be here

2020-12-17 12:47 UTC, Ilya-Krylov requested changes

2020-12-17 12:47 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/tests/expected_outputs/person-detection/person-detection-0203.json
> +{"map": 0.704}
for now, metric is measure in percent, 70.4 should be here

2021-01-11 08:24 UTC, Ilya-Krylov requested changes

2021-01-11 08:24 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/model_templates/person-detection/readme.md
> +### 7. Export PyTorch\* model to the OpenVINO format
?

2021-01-11 08:24 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/model_templates/person-detection/readme.md
> +To convert PyTorch\* model to the OpenVINO IR format run the `export.py` script:
?

2021-01-11 08:24 UTC, Ilya-Krylov commented on pytorch_toolkit/object_detection/model_templates/person-detection/readme.md
> +For SSD networks an alternative OpenVINO representation is saved automatically to `${WORK_DIR}/export/alt_ssd_export` folder.
?

2021-01-11 08:24 UTC, Ilya-Krylov commented
run tests

2021-01-12 08:37 UTC, GalyaZalesskaya commented
run tests

2021-01-13 11:12 UTC, Ilya-Krylov commented
run tests

2021-01-15 10:15 UTC, GalyaZalesskaya commented
run tests

2021-01-18 08:49 UTC, GalyaZalesskaya commented
@Ilya-Krylov tests finally passed and changes from your [PR](https://github.com/openvinotoolkit/training_extensions/pull/411) with template fixes were applied. Could you please approve these changes?

2021-01-18 08:53 UTC, Ilya-Krylov approved these changes

2021-01-18 08:53 UTC, merged