Develop new
openvinotoolkit/training_extensions pull request #461
Opened 2021-03-04 10:11 UTC by Ilya-Krylov

* removed useless run* scripts that were part of test system
* hid web ote since it is not supported
* hid tf models inside Misc folder and mark them as unsupported
* hid pt models (non-template) inside Misc folder and mark some of them as unsupported
* divided ote tests and models tests

2021-03-04 10:44 UTC, evgeny-izutov commented on models/text_spotting/model_templates/alphanumeric-text-spotting/text-spotting-0003/template.yaml
> +    epochs: 24
the easy fix) :1st_place_medal:

2021-03-04 11:12 UTC, evgeny-izutov approved these changes
Previously reviewed too, so no objection.

2021-03-04 18:34 UTC, LeonidBeynenson requested changes
2 @Ilya-Krylov :
Ilya, please, remove the function `run_tests_by_pattern` from the files `ote/ote/tests/utils.py` and `models/action_recognition_2/tests/common/utils.py`.
"This is not required any more"
Most probably, the entire file `models/action_recognition_2/tests/common/utils.py` should be removed too.

2021-03-05 06:19 UTC, merged

2021-03-05 07:01 UTC, Ilya-Krylov commented
@LeonidBeynenson https://github.com/openvinotoolkit/training_extensions/pull/463