Custom instance segmentation
openvinotoolkit/training_extensions pull request #467
Opened 2021-03-05 09:05 UTC by GalyaZalesskaya

2021-03-05 09:16 UTC, Ilya-Krylov requested changes

2021-03-05 09:16 UTC, Ilya-Krylov commented on models/instance_segmentation/model_templates/custom-instance-segmentation/readme.md
> +### 0. Change a directory in your terminal to instance_segmentation and activate venv.
please start indexing with 1

2021-03-05 09:16 UTC, Ilya-Krylov commented on models/instance_segmentation/model_templates/custom-instance-segmentation/readme.md
> +or if You use conda:
please do not mention `conda`

2021-03-05 09:16 UTC, Ilya-Krylov commented on models/instance_segmentation/model_templates/custom-instance-segmentation/readme.md
> +Instead of passing `snapshot.pth` you need to pass path to `model.bin` (or `model.xml`).
please remove `  (or 'model.xml')`

2021-03-05 09:16 UTC, Ilya-Krylov commented on ote/ote/api.py
> +        parser.add_argument('--opset', type=int, default=10, help='ONNX opset')
it should not be here, for now at least.

Does opset=11 not work for everything?

2021-03-10 20:35 UTC, GalyaZalesskaya commented
run tests

2021-03-12 06:29 UTC, Ilya-Krylov commented
deep-object-reid commit should not be changed I guess

2021-03-12 08:37 UTC, Ilya-Krylov approved these changes

2021-03-12 08:37 UTC, merged