Integration ModelAPI to anomaly
openvinotoolkit/training_extensions pull request #745
Opened 2021-12-01 09:44 UTC by akorobeinikov

Based on openvinotoolkit/anomalib#10

2021-12-03 08:26 UTC, druzhkov-paul commented
It may make sense to split this PR into two: one for SDK changes and another one for anomaly support. Though if anomaly is already Ok, I'm fine to merge it in one run. @akorobeinikov @samet-akcay

2021-12-03 10:45 UTC, samet-akcay requested changes
I feel like `external/anomaly/ote_anomalib/inference/inference.py` has significant amount of duplication with [ote-sdk exportable code inferencer](https://github.com/openvinotoolkit/training_extensions/blob/develop/ote_sdk/ote_sdk/usecases/exportable_code/inference/inference.py) and [anomalib.core.inferencer](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/core/model/inference.py). I think that we could utilize those inferencer objects rather than doing a copy-paste here. 

@ashwinvaidya17 and @djdameln I'd love to hear your thoughts here since you guys work on ote-sdk, anomalib and ote-anomalib inferencer codes

2021-12-03 10:45 UTC, samet-akcay commented on external/anomaly/anomaly_classification/openvino.py
> +from anomalib.core.model import model_wrappers
not sure if this exists in `anomalib.core.model`

2021-12-03 10:45 UTC, samet-akcay commented on external/anomaly/anomaly_classification/openvino.py
> +from anomalib.core.model import model_wrappers
any comments @djdameln, @ashwinvaidya17

2021-12-03 10:45 UTC, samet-akcay commented on external/anomaly/anomaly_classification/openvino.py
> +            update_progress_callback(int(i / dataset_size * 100))
If we use `dataset_size = len(dataset)` from L121 only in L125, then we could perhaps just call `update_progress_callback(int(i / len(dataset) * 100))` in L125. We would save a line there and the code could still be readable

2021-12-03 10:45 UTC, samet-akcay commented on external/anomaly/anomaly_classification/openvino.py
> +               output_model: ModelEntity) -> None:
I guess `black` is not run here.

2021-12-03 10:45 UTC, samet-akcay commented on external/anomaly/ote_anomalib/inference/model_wrappers/anomaly_classification.py
> +    def __init__(self, model_adapter, configuration=None, preload=False):
Would be nice to see the type of the variables. Otherwise, it's hard to read

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/utils.py
> +def get_model_path(path):
would be nice to annotate the variables like
`def get_model_path(path: str)`

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/utils.py
> +def get_parameters(path):
would be nice to annotate the variables like
def get_model_path(path: str)

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/utils.py
> +        if not os.path.exists(parameters_path):
Here we are using both `Path` and `os.path` packages. Would be good to use one of them.

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/utils.py
> +        if not os.path.exists(parameters_path):
Something like,

```
parameters_path = Path(__file__).parent / "config.json"
        if not parameters_path.exists():
```

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/utils.py
> +def create_model(model_path=None, config_file=None):
Type of `model_path` and `config_file`? `str`?

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/utils.py
> +def create_output_converter(labels, config_file=None):
Type of `labels` and `config_file`?

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +        self, predictions: np.ndarray, metadata: Dict = None
Not sure how pylint and mypy would be happy with `metadata: Dict = None`. I think it should be `metadata: Optional[Dict] = None`

2021-12-03 10:45 UTC, samet-akcay commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +        raise ValueError(converter_type)
would be something like
```
raise ValueError(f"Unknown converter type {converter_type}")
```
to understand the error better when encountered.

2021-12-03 13:32 UTC, druzhkov-paul commented
run ote_sdk tests

2021-12-03 14:03 UTC, Ilya-Krylov requested changes

2021-12-03 14:03 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/utils/shape_drawer.py
> +            text += f"{label.probability:.0%}" if label.probability <= 1.0 else f"{label.probability:.0f}%"
hmm, what if consider the same task and one object has probability = 0.9 and another has 1.1. What we will se then?
90% and 1%? Where does probability greater than 1 come from?

2021-12-03 14:03 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/sync.py
> +        help="Required. An input to process. The input must be a single image.",
Single image is the only supported thing?

2021-12-03 14:03 UTC, Ilya-Krylov commented on external/anomaly/ote_anomalib/inference/inference.py
> +    def converter(self):
What is it?

2021-12-03 14:03 UTC, Ilya-Krylov commented on external/anomaly/ote_anomalib/inference/inference.py
> +class Inferencer(ABC):
should not it be in OTE SDK?

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +def create_converter(converter_type: Domain, labels: List[Union[str, LabelEntity]]):
What about the return type?

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +def create_converter(converter_type: Domain, labels: List[Union[str, LabelEntity]]):
What if we need to pass a list of `Label`s (class derived from `LabelEntity`)?

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +    return LabelEntity(str(labels_map[index]), label_domain)
It is better to return the label object from the input list, rather than create a new one with the same label name. Now the id is not preserved at least.

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +from openvino.model_zoo.model_api.models import utils
Corporate wants you to find the difference.

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +    Simple fabric for converters based on type of tasks
```suggestion
    Simple factory for converters based on type of tasks
```

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +                get_label(self.labels_map, int(box.id), Domain.DETECTION), box.score
Is `box.score` guaranteed to be Python `float`? Please verify that this is so everywhere.

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +                    Rectangle(coords[0], coords[1], coords[2], coords[3]),
Ditto

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +            i + 1: get_label(labels, i, Domain.SEGMENTATION) for i in range(len(labels))
I have a feeling that this code can be simplified. 😄

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/prediction_to_annotation_converter.py
> +        self, predictions: List[Tuple], metadata: Dict[str, Any]
What are the types of tuple elements?

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/setup.py
> +    entry_points={"console_scripts": [f"{packages[0]}={packages[0]}.sync:main"]},
So, the demo script will still be inside the package?

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/sync.py
> +    Main function that is used for run demo.
```suggestion
    Main function that is used to run demo.
```

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/utils.py
> +    Create model using ModelAPI fabric
```suggestion
    Create model using ModelAPI factory
```

2021-12-03 15:24 UTC, druzhkov-paul commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/sync.py
> +    model = create_model(args.model)
Do we need config file here as well?

2021-12-03 15:28 UTC, druzhkov-paul commented
@akorobeinikov Please install [pre-commit](https://pre-commit.com/#installation) to run style checks automatically for your code.

2021-12-03 16:11 UTC, ashwinvaidya17 commented on external/anomaly/anomaly_classification/openvino.py
> +from anomalib.core.model import model_wrappers
I guess this is meant to be `ote_anomalib.inference.model_wrappers`

2021-12-03 16:11 UTC, ashwinvaidya17 commented on external/anomaly/anomaly_classification/configs/configuration.py
> +    class __InferenceParameters(ParameterGroup):
Do we need this? Seems like its reference is to get `class_name`. In that case we can just hard code `anomaly_classification`. I don't expect it to change as this task is  `anomaly_classification` already.

2021-12-03 16:11 UTC, ashwinvaidya17 commented on external/anomaly/anomaly_classification/configs/padim/configuration.yaml
> +inference_parameters:
Where is this accessed?

2021-12-03 16:11 UTC, ashwinvaidya17 commented on external/anomaly/anomaly_classification/configs/padim/configuration.yaml
> +    value: ssd
Why is this `ssd`?

2021-12-03 16:11 UTC, ashwinvaidya17 commented on external/anomaly/anomaly_classification/configs/stfpm/configuration.yaml
> +    value: ssd
Same here

2021-12-03 16:11 UTC, ashwinvaidya17 commented on external/anomaly/ote_anomalib/inference/inference.py
> +class OpenVINOInferencer(Inferencer):
I guess the only major change here is the OpenVINOInferencer. It would be nice if this change is made to `anomalib`. I can understand 2 PRs is a bit tedious. But, it will be easier to maintain while reducing duplication of code.

2021-12-13 13:17 UTC, samet-akcay commented
@akorobeinikov, when you are done with your changes, can you let me know so that I could go for the second round of review. Thanks!

2021-12-13 14:09 UTC, akorobeinikov commented
> @akorobeinikov, when you are done with your changes, can you let me know so that I could go for the second round of review. Thanks!

I think you can start second round of review.. After discussion in this PR, I decided to save interface for inference is `ote_sdk` and realizations in `anomalib`. Also model_wrappers saved in `ote_anomalib`. FYI @ashwinvaidya17

2021-12-16 06:27 UTC, Ilya-Krylov commented
@akorobeinikov will it be closed and https://github.com/openvinotoolkit/training_extensions/pull/782 used instead?

2021-12-16 09:04 UTC, akorobeinikov commented
> @akorobeinikov will it be closed and #782 used instead?

Yes, it will be closed

2021-12-16 10:49 UTC, closed without merging